project:
  type: website
  output-dir: docs

website:
  title: "Dr Steven Turnbull"
  navbar:
    left:
      - icon: github
        href: https://github.com/sturbull/
      - icon: linkedin
        href: https://www.linkedin.com/in/steven-turnbull-122b73156/
      - text: Home
        href: index.qmd 
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

