project:
  type: website
  output-dir: docs

website:
  title: "Dr Steven Turnbull"
  navbar:
    left:
      - icon: github
        href: https://github.com/sturbull/
      - icon: linkedin
        href: https://www.linkedin.com/in/steven-turnbull-122b73156/
      - text: Blog
        href: blog.qmd

format:
  html:
    template-partials: 
      - title-block.html
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    title-block-banner: true

editor: visual

execute:
  freeze: auto

